import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { AuthProvider } from '../contexts/AuthContext';
import { NavBar } from '../components/nav-bar';
import CssBaseline from '@mui/material/CssBaseline';
import Container from '@mui/material/Container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <AuthProvider>
              <NavBar />
              <Container
                maxWidth="xl"
                sx={{
                  mt: 4,
                  mb: 4
                }}
              >
                {children}
              </Container>
            </AuthProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
